const int ledPin = 12; // the pin that the LED is attached to
int incomingByte;      // a variable to read incoming serial data into

void setup() {
  // initialize serial communication:
  Serial.begin(9600);
  // initialize the LED pin as an output:
  pinMode(ledPin, OUTPUT);
}

void loop() {
  if (Serial.available() > 0) {
    incomingByte = Serial.read();
    if (incomingByte == ' ') {
      digitalWrite(ledPin, LOW);
      delay(3500);
    }
    if (incomingByte == 'A') {
      digitalWrite(2, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(2, LOW);
      digitalWrite(6, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(9, LOW);
      digitalWrite(5, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      delay(1500);
    }
    if (incomingByte == 'B') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'C') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'D') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(9, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'E') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'F') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      delay(1500);
    }
    if (incomingByte == 'G') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(8, LOW);
      digitalWrite(9, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'H') {
      digitalWrite(10, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(9, LOW);
      digitalWrite(2, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'I') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(7, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'J') {
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(8, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'K') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(2, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'L') {
      digitalWrite(10, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(6, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'M') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'N') {
      digitalWrite(11, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(9, LOW);
      digitalWrite(3, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'O') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'P') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      delay(1500);
    }
    if (incomingByte == 'Q') {
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(9, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(9, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'R') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(4, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'S') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'T') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(7, LOW);
      digitalWrite(3, LOW);
      delay(1500);
    }
    if (incomingByte == 'U') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'V') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(8, LOW);
      digitalWrite(3, LOW);
      delay(1500);
    }
    if (incomingByte == 'W') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(6, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(6, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
    if (incomingByte == 'X') {
      digitalWrite(10, HIGH);
      digitalWrite(A1, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(8, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(5, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A1, LOW);
      digitalWrite(7, LOW);
      digitalWrite(8, LOW);
      digitalWrite(2, LOW);
      digitalWrite(5, LOW);
      delay(1500);
    }
    if (incomingByte == 'Y') {
      digitalWrite(10, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(7, LOW);
      digitalWrite(3, LOW);
      delay(1500);
    }
    if (incomingByte == 'Z') {
      digitalWrite(10, HIGH);
      digitalWrite(11, HIGH);
      digitalWrite(A0, HIGH);
      digitalWrite(7, HIGH);
      digitalWrite(2, HIGH);
      digitalWrite(3, HIGH);
      digitalWrite(4, HIGH);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(1500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      delay(500);
      digitalWrite(ledPin, HIGH);
      delay(500);
      digitalWrite(ledPin, LOW);
      digitalWrite(10, LOW);
      digitalWrite(11, LOW);
      digitalWrite(A0, LOW);
      digitalWrite(7, LOW);
      digitalWrite(2, LOW);
      digitalWrite(3, LOW);
      digitalWrite(4, LOW);
      delay(1500);
    }
  }
}
